import { useRef } from 'react'
import { PDF } from './PDF'
import { Button } from '@mui/material'
import { useTranslation } from 'react-i18next'
import { useDialog } from '../../../components/DialogProvider'
//import html2pdf from 'html2pdf.js'
import { useReactToPrint } from 'react-to-print'

const Report = ({ data }) => {
  const componentRef = useRef()
  const [openDialog, closeDialog] = useDialog()

  /*
  REVISAR: no puedo instalar html2pdf
  install --save html2pdf.js
  ERROR: se ha denegado el acceso a la ruta de acceso al Registro.
*/
  // function handlePrint() {
  //   const options = {
  //     filename: 'my-document.pdf',
  //     margin: 1,
  //     image: { type: 'jpeg', quality: 0.98 },
  //     html2canvas: { scale: 2 },
  //     jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' },
  //     header:
  //       '<div style="text-align:center;">Page <span class="page"></span> of <span class="total"></span></div>',
  //     footer:
  //       '<div style="text-align:center;">Generated by my app on ' +
  //       new Date().toLocaleDateString() +
  //       '</div>',
  //   }
  //   html2pdf().set(options).from(componentRef.current).save()
  // }

  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
  })

  const { t } = useTranslation()

  // openDialog({
  //   children: <PDF ref={componentRef} onClose={closeDialog}></PDF>,
  // })

  return (
    <div style={{ width: 1145, margin: '0 auto' }}>
      <div style={{ backgroundColor: 'white', padding: 15, marginBottom: 20 }}>
        <Button onClick={handlePrint} style={{ backgroundColor: '#b9db42' }}>
          {t('IMPRIMIR')}
        </Button>
      </div>
      <PDF data={data} ref={componentRef} />
    </div>
  )
}

export default Report
